
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "164c61bed44e13191cdd8df1c2239cd2300d1d1e",
 "version": "4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
