
# This file was generated by 'versioneer.py' (0.10) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.8'
version_full = 'a138dcd9e9494f85004fd0ccdb715edf73a3cb66'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

