
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f2786bd6e5ed999a46746f5607f29983c1be0bc4",
 "version": "3.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
